functionalvibes/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import include, url
from django.urls import path, re_path  # include
from django.views.generic import TemplateView
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve
from .views import (
    TeamList,
    Testimonials,
    MemberVideos,
    VibesInAction,
    VibesInActionVideo,
    Jobs,
    HowWeRoll,
    FaqsList,
    BlogList, PostView,
    NoMember,
    TeamMemberView,
    ServicesList,
    ServiceView,
    ContactView,
    ContactSuccess,

    subscribe,
    GuideQuestionaryView,
    GuideQuestionarySuccess,
    downloadable_file, price_list_file, get_price_list
)


admin.autodiscover()

urlpatterns = [
    url(r'^sitemap\.xml$', sitemap,
        {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^team/', TeamList.as_view(), name='team'),
    url(r'^contact/', ContactView.as_view(), name='contact'),
    url(r'^contact-success/', ContactSuccess.as_view(), name='contact_success'),

    url(r'^subscribe/', subscribe, name="subscribe"),
    url(r'^get-price-list/', get_price_list, name="get_price_list"),
    url(r'^guide-questionary/', GuideQuestionaryView.as_view(), name='guide_questionary'),
    url(r'^guide-questionary-success/', GuideQuestionarySuccess.as_view(), name='guide_questionary_success'),
    # url(r'^', downloadable_file, name="downloadable_file"),
    # url(r'^downloadable_file/(?P<unique_id>[-\w]+)/$', downloadable_file, name="downloadable_file"),
    url(r'^downloadable_file/$', downloadable_file, name="downloadable_file"),
    url(r'^price_list_file/$', price_list_file, name="price_list_file"),

    url(r'^coach-book-request/', ContactSuccess.as_view(), name='coach_book_request'),
    url(r'^event-request-success/', ContactSuccess.as_view(), name='event_request_success'),
    url(r'^testimonials/', Testimonials.as_view(), name='testimonials'),
    url(r'^services', ServicesList.as_view(), name='services'),
    url(r'^service/(?P<slug>[-\w]+)/$', ServiceView.as_view(), name='single_service'),
    url(r'^jobs/', Jobs.as_view(), name='jobs'),
    url(r'^members/', MemberVideos.as_view(), name='members'),
    # url(r'^vibes-in-action/', VibesInAction.as_view(), name='vibes_in_action'),
    # url(r'^vibes-video/(?P<pk>\d+)/$', VibesInActionVideo.as_view(), name='vibes_video_detail'),
    url(r'^vibes-video/(?P<pk>\d+)/$', VibesInActionVideo.as_view(), name='vibes_video_detail'),
    url(r'^member/(?P<slug>[-\w]+)/$', TeamMemberView.as_view(), name='team_member'),
    url(r'^how-we-roll/', HowWeRoll.as_view(), name='how_we_roll'),
    url(r'^faq/', FaqsList.as_view(), name='faqs_list'),
    url(r'^blog/', BlogList.as_view(), name='blog_list'),
    path('article/<str:slug>', PostView.as_view(), name='post_detail'),
    url(r'^member-login', NoMember.as_view(), name='password_form_view'),
    url(r'^events/', include(('cmsplugin_events.urls', 'calendar'), namespace='events')),
    url(r'^8sdimkl9/', admin.site.urls),  # NOQA
    path('editor/', include('django_summernote.urls')),
    url(r'^', include('cms.urls')),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
] + staticfiles_urlpatterns()

# urlpatterns += i18n_patterns(
#     url(r'^admin/', admin.site.urls),  # NOQA
#     url(r'^', include('cms.urls')),
# )

# This is only needed when using runserver.
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
        url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
        # url(r'^media/(?P<path>.*)$', serve,
        #     {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ] + staticfiles_urlpatterns() + urlpatterns

functionalvibes/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from autoslug import AutoSlugField
from django.utils import timezone


class Language(models.Model):
    name = models.CharField(max_length=120)
    abbreviation = models.CharField(max_length=120, null=True, blank=True)
    icon = models.ImageField(upload_to='images/languages', null=True)

    class Meta:
        verbose_name = 'Language'
        verbose_name_plural = 'Languages'

    def __str__(self):
        return self.name


class Slide(models.Model):
    active = models.BooleanField(default=True)
    title = models.CharField(max_length=120)
    order = models.IntegerField(default=0)

    photo = models.ImageField(
        upload_to='slides',
        help_text='width 2400px, height 1100px'
    )

    subtitle = models.CharField(max_length=240, blank=True, null=True)

    button_text = models.CharField(max_length=120, blank=True, null=True)
    button_link = models.CharField(max_length=220, blank=True, null=True)

    second_button_text = models.CharField(max_length=120, blank=True, null=True)
    second_button_link = models.CharField(max_length=220, blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Slides'


class Service(models.Model):
    title = models.CharField(max_length=120)
    slug = AutoSlugField(populate_from='title', editable=True, null=True, blank=True)
    order = models.IntegerField(blank=True, null=True)
    active = models.BooleanField(default=True)
    subtitle = models.CharField(max_length=220, null=True, blank=True)
    photo = models.ImageField(upload_to='images/services', null=True, blank=True)
    description = models.TextField(blank=True, null=True)
    email = models.CharField(max_length=120, null=True, blank=True)
    telephone = models.CharField(max_length=120, null=True, blank=True)
    custom_read_more_link = models.CharField(max_length=320, null=True, blank=True)

    class Meta:
        verbose_name = 'Service'
        verbose_name_plural = 'Services'

    def __str__(self):
        return self.title


class TeamMember(models.Model):
    name = models.CharField(max_length=120)
    # slug = models.SlugField(max_length=125)
    slug = AutoSlugField(populate_from='name', editable=True, null=True, blank=True)
    order = models.IntegerField(blank=True, null=True)
    active = models.BooleanField(default=True)
    position = models.CharField(max_length=120, null=True, blank=True)
    photo = models.ImageField(upload_to='images/team', null=True, blank=True)
    language = models.ManyToManyField(Language, blank=True)
    description = models.TextField(blank=True, null=True)
    email = models.CharField(max_length=120, null=True, blank=True)
    telephone = models.CharField(max_length=120, null=True, blank=True)
    facebook = models.CharField(max_length=120, null=True, blank=True)
    twitter = models.CharField(max_length=120, null=True, blank=True)
    linkedin = models.CharField(max_length=120, null=True, blank=True)
    instagram = models.CharField(max_length=120, null=True, blank=True)

    class Meta:
        verbose_name = 'Team member'
        verbose_name_plural = 'Team members'

    def __str__(self):
        return self.name


class TestimonialCategories(models.Model):
    name = models.CharField(max_length=320)
    order = models.IntegerField(blank=True, null=True)
    active = models.BooleanField(default=True)
    description = models.TextField(blank=True, null=True)

    class Meta:
        verbose_name = 'Testimonial category'
        verbose_name_plural = 'Testimonial categories'

    def __str__(self):
        return self.name


class Testimonial(models.Model):
    title = models.CharField(max_length=320)
    order = models.IntegerField()
    category = models.ManyToManyField(TestimonialCategories,)
    subtitle = models.CharField(max_length=550, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    top_story = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    slide = models.ImageField(upload_to='images/reviews', null=True, blank=True)
    reviewer = models.CharField(max_length=150, blank=True, null=True)
    photo = models.ImageField(upload_to='images/reviewer', null=True, blank=True)
    stars = models.IntegerField(blank=True, null=True, help_text='From 1 to 5 stars rating if needed')

    class Meta:
        verbose_name = 'Testimonial'
        verbose_name_plural = 'Testimonials'

    def __str__(self):
        return self.title


class Member(models.Model):
    name = models.CharField(max_length=320)
    active = models.BooleanField(default=True)
    email_address = models.CharField(max_length=150, blank=True, null=True)
    password = models.CharField(max_length=150, blank=True, null=True)
    notes = models.TextField(blank=True, null=True)

    class Meta:
        verbose_name = 'Member'
        verbose_name_plural = 'Member'

    def __str__(self):
        return self.name


class MemberVideoArea(models.Model):
    vibes_in_action = models.BooleanField(default=False)
    members_area = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Video area'
        verbose_name_plural = 'Video areas'
        unique_together = ['vibes_in_action', 'members_area']

    def __str__(self):
        return 'Vibes_in_action' if self.vibes_in_action else 'Members_area'

class MemberVideo(models.Model):
    title = models.CharField(max_length=320)
    active = models.BooleanField(default=True)
    order = models.IntegerField(blank=True, null=True)
    display_at = models.ForeignKey(MemberVideoArea, null=True, on_delete=models.SET_NULL)
    subtitle = models.CharField(max_length=550, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    vimeo = models.CharField(max_length=550, blank=True, null=True)
    youtube = models.CharField(max_length=550, blank=True, null=True)

    class Meta:
        verbose_name = 'Video'
        verbose_name_plural = 'Videos'

    def __str__(self):
        return self.title


class HowWeRollPoint(models.Model):
    order = models.IntegerField(blank=True, null=True)
    active = models.BooleanField(default=True)
    title = models.CharField(max_length=320)
    subtitle = models.CharField(max_length=550, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='images/how_we_roll', null=True, blank=True)

    class Meta:
        verbose_name = 'How We Roll Point'
        verbose_name_plural = 'How We Roll Points'

    def __str__(self):
        return self.title


class Contact(models.Model):
    name = models.CharField(max_length=150)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             blank=True, null=True,
                             on_delete=models.CASCADE)
    # user = models.ForeignKey(get_user_model(), blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    subject = models.CharField(max_length=80, blank=True, null=True)
    phone = models.CharField(max_length=18, blank=True, null=True)
    message = models.TextField(max_length=1020)
    date = models.DateTimeField(auto_now=True, blank=True)

    class Meta:
        verbose_name = '01 Contact request'
        verbose_name_plural = '01 Contact requests'

    def __str__(self):
        return self.name


class BookCoach(models.Model):
    name = models.CharField(max_length=150)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             blank=True, null=True,
                             on_delete=models.CASCADE)
    # user = models.ForeignKey(get_user_model(), blank=True, null=True)
    phone = models.CharField(max_length=18, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    coach = models.CharField(max_length=80, blank=True, null=True)
    date_created = models.DateTimeField(auto_now=True, blank=True)
    date_requested = models.DateTimeField(auto_now=True, blank=True)
    comments = models.TextField(max_length=1020, blank=True, null=True)

    class Meta:
        verbose_name = '02 Coach request'
        verbose_name_plural = '02 Coach request'

    def __str__(self):
        return self.name


class BookEvent(models.Model):
    date_created = models.DateTimeField(auto_now=True, blank=True)
    name = models.CharField(max_length=150)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             blank=True, null=True,
                             on_delete=models.CASCADE)
    # user = models.ForeignKey(get_user_model(), blank=True, null=True)
    phone = models.CharField(max_length=18, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    event = models.CharField(max_length=80, blank=True, null=True)
    comments = models.TextField(max_length=1020, blank=True, null=True)

    class Meta:
        verbose_name = '03 event participation'
        verbose_name_plural = '03 event participations'

    def __str__(self):
        return '%s (%s)' %(self.event, self.name)


class Subscribe(models.Model):
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email_id = models.EmailField(null=True, blank=True)
    timestamp = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return '%s %s (%s)' %(self.first_name, self.last_name, self.email_id)


class QuestionaryFreeAssessment(models.Model):
    option = models.CharField(max_length=250)

    def __str__(self):
        return self.option


class QuestionaryReceiveOffer(models.Model):
    option = models.CharField(max_length=250)

    def __str__(self):
        return self.option


class GuideFile(models.Model):

functionalvibes/templates/contact.html
{% extends 'base_front.html' %}
{% load sekizai_tags static %}
{% load social_share %}


{% block content %}
<head>
    <title>
        Contatti - Functional Vibes
    </title>
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
    {% block facebook_opengraph %}
    <!-- Facebook Opengraph -->
    <meta property="og:url" content="https://functionalvibes.com/contact" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="Contatti - Functional Vibes" />
    <meta property="og:description" content="Functional Training sessions, Osteopathy, Nutritional Consultancy and Postural Assessment. A totally new concept of health consultancy, right in the heart of Brussels"/>
    <meta property="og:image" content="https://it.functionalvibes.com/static/images/get_in_touch.jpg" />
    <meta property="og:image:alt" content="Contatti - your movement experience" />
    <meta property="fb:app_id" content="3625437754143193"/>
    <meta property="og:image:type" content="image/png" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />
    {% endblock facebook_opengraph %}

</head>
    <div class="wrapper">
        <section class="maps-container">
            <div class="map"
                 data-addresses="[43.667104, 10.644509]"
                 data-info="[Functional Vibes Società Sportiva Dilettantistica a RL<br/>Via Tosco - Romagnola 201/C, 56025 - Pontedera, PI]"
                 data-icon="{% static 'images/map-icon.png' %}" data-zoom="15"></div>{# , [44.2507913, 16.3983171] #}
        </section>

        <section class="module divider-top">
            <div class="service-container" style="margin-right: -10px;padding:15px">
                <div class="row">
                    <div class="col-lg-6 col-md-9 m-auto text-center" >
                        <h1>Contattaci subito!</h1>
                        <p class="lead" style="font-size:18px;">
                            Sei letteralmente a un passo da una svolta epocale nella tua vita.<br/>
                            Inserisci qui sotto i tuoi dati e la tua richiesta per una consulenza gratuita e
                            riceverai una nostra risposta entro le prossime 24 ore!
                        </p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="space" data-MY="60px"></div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6" style="padding-left: 50px;padding-top: 30px;padding-right:70px!important;">
                        <form role="form"
                              action="."
                              enctype="multipart/form-data"
                              method="post">

                            {% csrf_token %}

                            {% if form.errors %}
                                <div class="alert alert-error">
                                    <ul>
                                        {% for error in form.non_field_errors %}
                                            <li>{{ error }}</li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            {% endif %}

                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <input class="form-control" type="text" name="name" id="id_name"
                                               placeholder="Name*" required="required"
                                               style="border: 2px solid #6c757d;">
                                        <p class="help-block text-danger"></p>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <input class="form-control" type="email"
                                               name="email" id="id_email" placeholder="E-mail*"
                                               required="required" style="border: 2px solid #6c757d;">
                                        <p class="help-block text-danger"></p>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <input class="form-control" type="text"
                                               name="subject" id="id_subject" placeholder="Subject"
                                               style="border: 2px solid #6c757d;">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <textarea class="form-control"
                                                  name="message" id="id_message" placeholder="Message*"
                                                  rows="12" required="required" style="border: 2px solid #6c757d;"></textarea>
                                    </div>
                                </div>
                                <div class="col-md-12">

                                    {{ form.captcha }}

                                    <br/>

                                    <input class="btn btn-square btn-outline-secondary m-b-30 text-left"
                                           type="submit"
                                           value="Send Message">
                                    {#<a class="btn btn-square btn-outline-secondary m-b-30 text-left"#}
                                            {#name="submit-form"#}
                                            {#type="submit">#}
                                        {#Send Message#}
                                    {#</a>#}

                                </div>
                            </div>
                        </form>
                        {#<!-- Ajax response-->#}
                        {#<div class="ajax-response text-center" id="contact-response"></div>#}
                    </div>

                    <div class="col-md-6">
                        <div class="team-item">
                            <div class="img-container">
                                <img src="{% static 'images/get_in_touch.jpg' %}" alt="Get in touch photo">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section class="module-cover para-desktop text-center"
                 style='height: 100%;background-image: url("{% static 'images/virtual_tour_1.jpg' %}");'>
            <div class="container">
                <div class="row">
                    <div class="over-title-center">
                        <a href="/virtual-tour/">
                            <h3 class="m-b-20 over-title text-center" style="width: 8em;">
                                Tour virtuale
                            </h3>
                        </a>
                    </div>
                </div>
            </div>
        </section>

        {#{% post_to_facebook object_or_url "Post to Facebook!" %}#}
    </div>
{% endblock content %}

functionalvibes/templates/faqs.html
{% extends 'base_front.html' %}
{% load sekizai_tags static %}
{% load social_share %}


{% block content %}
<head>
    <title>
        Domande frequenti - Functional Vibes
    </title>

    {% block facebook_opengraph %}
    <!-- Facebook Opengraph -->
    <meta property="og:url" content="https://functionalvibes.com/jobs/" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="Domande frequenti - Functional Vibes" />
    <meta property="og:description" content="Functional Training sessions, Osteopathy, Nutritional Consultancy and Postural Assessment. A totally new concept of health consultancy, right in the heart of Brussels"/>
    <meta property="og:image" content="https://it.functionalvibes.com/static/images/team1.jpg" />
    {#<meta property="og:image" content="{{ team_member.photo.url }}" />#}
    <meta property="og:image:alt" content="Domande frequenti - Functional Vibes" />
    <meta property="fb:app_id" content="3625437754143193"/>
    <meta property="og:image:type" content="image/png" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />
    {% endblock facebook_opengraph %}
</head>
    <div class="wrapper">
        <section class="module-cover text-center para-desktop"
                 style='background-image: url("{% static 'images/virtual_tour_1.jpg' %}");padding:0;'>{#parallax#}
            <div class="container">
                <div class="row">
                    <div class="over-title-center" style="padding-top:200px">
                        <h3 class="text-center" style="color: #333333; background-color: #ffffff;padding:20px" >
                            <b>Domande frequenti</b>
                        </h3>
                    </div>
                </div>
            </div>
        </section>

        <section class="module bg-gray p-t-0 p-b-40">
            <div class="container">
                <div class="space" data-MY="-60px"></div>
                <div class="row">
                </div>
            </div>
        </section>

        <section style="padding-top: 40px">
            <div class="row">
                <div class="col-md-2"></div>

                <div class="col-md-8">
                    <div class="accordion" id="accordion1">

                        {% for faq in faqs %}
                            <div class="accordion-item">
                               <div class="accordion-item-header">
                                  <h6>
                                      <a class="accordion-link collapsed"
                                         data-toggle="collapse" href="#collapse-{{ faq.id }}"
                                         aria-expanded="false">
                                          {{ faq.title }}
                                      </a>
                                  </h6>
                               </div>
                               <div class="collapse" id="collapse-{{ faq.id }}" data-parent="#accordion1">
                                  <div class="accordion-item-body">
                                      <p class="faq-body">{{ faq.body|safe }}</p>
                                      {% if faq.id == 12 and price_list_exists %}
                                          <aside class="widget widget-recent-entries"
                                                   style="padding: 30px; background-color:#333333; color:white;">
                                                <p>
                                                    Hai bisogno del nostro listino prezzi?
                                                </p>
                                                <form class="form--merge form--no-labels form--active"
                                                      style="margin-top: -30px"
                                                      action="{% url 'get_price_list' %}"
                                                      enctype="multipart/form-data"
                                                      method="post"
                                                      id="subForm"
                                                      data-error="Please fill all fields correctly."
                                                      data-success="Thanks for signing up! Please check your inbox for confirmation email."
                                                      novalidate="novalidate">
                                                    {% csrf_token %}

                                                    {% if form.errors %}
                                                        <div class="alert alert-danger" role="alert">
                                                            <ul>
                                                               {% for field in form %}
                                                                  {% for error in field.errors %}
                                                                      <li>{{ error|escape }}</li>
                                                                  {% endfor %}
                                                               {% endfor %}
                                                            </ul>
                                                        </div>
                                                    {% endif %}

                                                    {% if form.errors %}
                                                        <div class="alert alert-danger" role="alert">
                                                            <ul>
                                                                {% for error in form.non_field_errors %}
                                                                    <li>{{ error }}</li>
                                                                {% endfor %}
                                                            </ul>
                                                        </div>
                                                    {% endif %}

                                                    <br>
                                                    <input class="col-md-3 col-sm-6 form-mar"
                                                           id="id_first_name"
                                                           name="first_name"
                                                           type="text" required
                                                           placeholder="Type your first name">
                                                    <input class="col-md-3 col-sm-6 form-mar"
                                                           id="id_last_name"
                                                           name="last_name"
                                                           type="text" required
                                                           placeholder="Type your last name">
                                                    <input class="col-md-3 col-sm-6 form-mar"
                                                           id="id_email_id"
                                                           name="email_id"
                                                           type="email" required
                                                           placeholder="Type your e-mail Address">
                            {#                        <button type="submit" class="btn">Go</button>#}
                        {#                            <a class="btn btn-outline-brand" href="#">Go</a>#}
                                                    <input class="btn btn-outline-brand form-mar"
                                                           type="submit"
                                                           value="Download it here">

                                                    <i class="newsletter-description">
                                                        <br/>
                                                        By entering your info, you will become a Functional Vibes buddy:
                                                        we will give you access to special offers and you will be the first to know about
                                                        cool events and initiatives aimed at taking control over your daily wellbeing.
                                                        We will also share with you a ton of good vibes and positivity because we strongly
                                                        believe that &quot;The journey towards a healthier you starts with a smile&quot;.
                                                            (Unsub anytime in a click) You also agree to our
                                                        <a href="/media/policy/Functional_Vibes_PRIVACY_FORM.pdf">
                                                            privacy
                                                        </a>.
                                                    </i>
                                                </form>
                                            </aside>
                                      {% endif %}
                                  </div>
                               </div>
                            </div>
                        {% endfor %}

                    </div>
                </div>

                <div class="col-md-2"></div>
            </div>
        </section>
    </div>
{% endblock content %}

functionalvibes/templates/off.tour.html
{% extends 'base_front.html' %}
{% load sekizai_tags static %}

{% block content %}
    <div class="wrapper">

    </div>
{% endblock content %}